version: "3.8"

services:
  chamados-db:
    image: mysql:5.7
    container_name: chamados-db
    ports:
      - "${MYSQL_PORT}:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    volumes:
      - dbdata:/var/lib/mysql

  chamados-api:
    build: .
    container_name: chamados-api
    ports:
      - "${PORT}:${PORT}"
    volumes:
      - .:/app
      - /app/node_modules
    env_file:
      - .env
    depends_on:
      - chamados-db

volumes:
  dbdata:
