version: "3.8"

services:
  chamados-db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    ports:
      - "${MYSQL_PORT}:3306"
    volumes:
      - dbdata:/var/lib/mysql

  chamados-api:
    build: .
    ports:
      - "${PORT}:3333"
    depends_on:
      - chamados-db
    volumes:
      - ./:/app
      - /app/node_modules
    environment:
      DATABASE_URL: ${DATABASE_URL}
      NODE_ENV: development
      JWT_SECRET: ${JWT_SECRET}
    command: npm run dev
    restart: unless-stopped

volumes:
  dbdata:
